# Generated by Django 6.0.4 on 2026-04-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=300, verbose_name='Ответ')),
                ('priority', models.PositiveIntegerField(choices=[(3, 'Важный'), (2, 'Менее важный'), (1, 'Не важный')], default=1, verbose_name='Приоритет вопроса')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ['-priority'],
                'indexes': [models.Index(fields=['priority'], name='mainsite_qu_priorit_b1f3bd_idx')],
            },
        ),
    ]
