# Generated by Django 6.0.4 on 2026-04-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован'),
        ),
    ]
